name: arya
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter


  # Firebase packages
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.0
  provider: ^6.1.5
  cloud_firestore: ^6.0.0

  
  
  # Assets cleaner
  assets_cleaner: ^0.1.5+12

  # Shared Preferences
  shared_preferences: ^2.5.3
  dio: ^5.9.0

  # Open Food Facts API
  openfoodfacts: ^3.24.0

  
  # Collection utilities
  collection: ^1.19.1

  # Translation and localization
  localization: ^2.1.1
  easy_localization: ^3.0.8

  #Navigation
  auto_route: ^10.1.2

  # Animations
  lottie: ^3.3.1

  # QR code scanner
  mobile_scanner: ^7.0.1
  
  # Image handling
  image_picker: ^1.2.0
  
  # Shimmer effect
  shimmer: ^3.0.0
  url_launcher: ^6.3.2

  mockito: ^5.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter




  flutter_lints: ^6.0.0

  build_runner: ^2.7.1
  auto_route_generator: ^10.0.2
  patrol: ^3.19.0
  patrol_cli: ^3.10.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/categories/
    - assets/lottie/
    - assets/translations/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package